# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-23 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enibar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='description',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pricedescription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='PriceDescription',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
