# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enibar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='foreign_id',
            field=models.IntegerField(unique=True),
        ),
    ]
