# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-01 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enibar', '0002_auto_20151123_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyline',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='historyline',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historyline',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
