# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enibar', '0006_auto_20160112_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyline',
            name='note',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
