# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-09 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20150924_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='externinscription',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
