# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-11-09 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20151016_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('manage_entries', 'Can manage user entries'), ('access_list', 'Can view user list (needed for csv export)'))},
        ),
    ]
