# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-05 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20151016_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrentEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
                ('delay', models.IntegerField(default=1)),
                ('last_created', models.DateField(blank=True, default=None, null=True)),
            ],
            bases=('events.event',),
        ),
    ]
