# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_recurrentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='model',
            field=models.BooleanField(default=False),
        ),
    ]
