# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-11-10 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_model'),
        ('events', '0022_auto_20151109_2002'),
    ]

    operations = [
    ]
