# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-11-10 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('manage_entries', 'Can manage user entries'), ('manage_event', 'Can manage events (add/del/edit)'), ('access_list', 'Can view user list (needed for csv export)'))},
        ),
        migrations.AlterModelOptions(
            name='recurrentevent',
            options={'permissions': (('manage_recurrent_event', 'Can manage recurrent event (add/del/edit'),)},
        ),
    ]
