# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-11-14 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20151110_1757'),
        ('events', '0024_auto_20151113_1659'),
    ]

    operations = [
    ]
