# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def migrate_data(apps, schema_editor):
    ExternLink = apps.get_model('events', 'ExternLink')
    for entry in ExternLink.objects.all():
        entry.admin_uuid = uuid.uuid4()
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='externlink',
            name='admin_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(migrate_data),
    ]
