# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20151210_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
