# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20151211_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_contributor', models.IntegerField()),
                ('price_non_contributor', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='events.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='formula',
            unique_together=set([('name', 'event')]),
        ),
    ]
