# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20160104_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.Formula'),
        ),
    ]
