# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_inscription_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Formula'),
        ),
    ]
