# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_externinscription_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_extern_inscriptions',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='gestion',
            field=models.CharField(blank=True, choices=[(None, 'Pas de gestion'), ('WAF', 'Gestion style WAF'), ('NL', 'Gestion style no-limit'), ('FOR', 'Gestion formules')], default=None, max_length=3, null=True),
        ),
    ]
