# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20160106_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='price_contributor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='formula',
            name='price_non_contributor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
