# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('site', models.URLField(blank=True, null=True)),
                ('admins', models.ManyToManyField(related_name='adminstrated_assos', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='assos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
