# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0001_squashed_0003_auto_20160128_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asso',
            name='admins_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asso_admin_set', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='asso',
            name='members_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asso_set', to='auth.Group'),
        ),
    ]
