# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0002_auto_20160128_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='asso',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asso',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='asso_pictures'),
        ),
    ]
