# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-11-09 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userrequest_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequest',
            options={'permissions': (('manage_account_request', 'Can manage account request'),)},
        ),
    ]
