# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-23 18:36
from __future__ import unicode_literals

from django.db import migrations
from accounts.backends import normalize_username


def migrate_username(apps, schema_editor):
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        user.username = normalize_username(user.username)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20151109_1748'),
    ]

    operations = [
        migrations.RunPython(migrate_username)
    ]
