# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20151123_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 7, 11, 21, 3, 827112, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
