# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20150905_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinghistory',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Packs'),
        ),
        migrations.AlterField(
            model_name='buyinghistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
