# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_auto_20151110_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinghistory',
            name='seller',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
