# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logoDir', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
