# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0001_squashed_0009_auto_20161009_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='urlLink',
            field=models.URLField(max_length=300),
        ),
    ]
