# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20160213_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prof',
            options={'permissions': (('manage_prof', 'Can manage profs'),)},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': (('manage_quote', 'Can manage quotes'),)},
        ),
    ]
