# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0007_announcement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[(None, 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée')], max_length=8, null=True),
        ),
    ]
